-- AlterTable
ALTER TABLE "PlayerProfile" ADD COLUMN     "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN     "totalDeaths" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "totalKills" INTEGER NOT NULL DEFAULT 0;
